### ISSUE TITLE
Please make this work on Chromium Edge

### ISSUE THREAD

**Issue by NightYoshi370** [AlexejheroYTB/Dlockly#18]
As someone who is using the new Chromium Edge, I don't see why I need to switch to a different browser with the exact same engine just to use this.

**Comment by WilsontheWolf** [comment]
I belive this is removed in the dev branch. I havent tried chromium edge but see if you can install a user agent switcher for it

**Comment by AlexejheroYTB** [comment]
It should work now. Try it out

**Comment by NightYoshi370** [comment]
It works now. Thank you guys
